FLD_CONTEXT_SALESFORCE = "salesforce"
FLD_CONTEXT_SALESFORCE_CONSUMER_KEY = "consumerKey"
FLD_CONTEXT_SALESFORCE_CONSUMER_SECRET = "consumerSecret"
FLD_CONTEXT_SCHEDULE_EXPRESSION = "scheduleExpression"
FLD_CONTEXT_UPDATES_FROM_SF_BUCKET = "updatesFromSalesforceBucket"
FLD_CONTEXT_SF_DOMAIN = "domain"

LL_CDDO_UTILS = "cddo_utils-0.1.40"
