FLD_CONTEXT_SALESFORCE = "salesforce"
FLD_CONTEXT_SALESFORCE_CONSUMER_KEY = "consumerKey"
FLD_CONTEXT_SALESFORCE_CONSUMER_SECRET = "consumerSecret"
FLD_CONTEXT_SCHEDULE_EXPRESSION = "scheduleExpression"
FLD_CONTEXT_UPDATES_FROM_SF_BUCKET = "updatesFromSalesforceBucket"
FLD_CONTEXT_SF_DOMAIN = "domain"
FLD_CONTEXT_PROFILE = "profile"

LL_CDDO_UTILS = "cddo_utils-0.1.95"


FLD_CONTEXT_PRIVATESUBNETID1 = "PrivateSubnetId1"
FLD_CONTEXT_PRIVATESUBNETID2 = "PrivateSubnetId2"
FLD_CONTEXT_RDSSECRETNAME = "RdsSecretName"
FLD_CONTEXT_VPCID = "VpcId"
FLD_CONTEXT_BASTIONHOSTSG = "BastionHostSG"
